# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 19:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='second_num',
            new_name='second_number',
        ),
    ]
