# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_list', '0002_auto_20171115_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='second_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
